 menu98edb85b00d9527ad5acebe451b3fae6 = {     {"7-Zip FM", "7zFM", "/usr/share//icons/hicolor/32x32/apps/p7zip.png" },
     {"Application Finder", "xfce4-appfinder", "/usr/share//icons/gnome/16x16/actions/gtk-find.png" },
     {"Avant Window Navigator", "avant-window-navigator", "/usr/share//icons/hicolor/24x24/apps/avant-window-navigator.png" },
     {"Calculator", "gcalctool", "/usr/share//icons/gnome/16x16/apps/accessories-calculator.png" },
     {"Character Map", "gucharmap", "/usr/share//icons/gnome/16x16/apps/accessories-character-map.png" },
     {"KeePassX", "keepassx ", "/usr/share/pixmaps/keepassx.xpm" },
     {"Leafpad", "leafpad ", "/usr/share//icons/hicolor/16x16/apps/leafpad.png" },
     {"Orage Globaltime", "globaltime", "/usr/share//icons/hicolor/48x48/apps/orage_globaltime.png" },
     {"Parcellite", "parcellite", "/usr/share/pixmaps/parcellite.png" },
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"Screenshot", "xfce4-screenshooter", "/usr/share//icons/hicolor/48x48/apps/applets-screenshooter.png" },
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"Xarchiver", "xarchiver", "/usr/share//icons/hicolor/16x16/apps/xarchiver.png" },
     {"Xournal", "xournal "},
     {"gedit", "gedit ", "/usr/share//icons/gnome/16x16/apps/accessories-text-editor.png" },
 }

 menude7a22a0c94aa64ba2449e520aa20c99 = {     {"DrRacket", "drracket", "/usr/share/pixmaps/drracket.xpm" },
     {"R", "xterm -e R", "///usr/share/pixmaps/r.png" },
     {"Stellarium nightsky renderer", "stellarium", "/usr/share//icons/hicolor/16x16/apps/stellarium.png" },
 }

 menu251bd8143891238ecedc306508e29017 = {     {"Battle for Wesnoth", "wesnoth", "/usr/share/pixmaps/wesnoth-icon.png" },
     {"Battle for Wesnoth Map Editor", "wesnoth -e", "/usr/share/pixmaps/wesnoth_editor-icon.png" },
     {"DeSmuME (Gtk)", "desmume", "/usr/share/pixmaps/DeSmuME.xpm" },
     {"DeSmuME (Gtk-Glade)", "desmume-glade", "/usr/share/pixmaps/DeSmuME.xpm" },
     {"Dwarf Fortress", "dwarffortress", "///usr/share/pixmaps/dwarffortress.png" },
     {"FreeCol", "freecol", "///usr/share/pixmaps/freecol.xpm" },
     {"Freeciv", "freeciv-gtk2", "/usr/share//icons/hicolor/16x16/apps/freeciv-client.png" },
     {"Freeciv modpack installer", "freeciv-modpack", "/usr/share//icons/hicolor/16x16/apps/freeciv-modpack.png" },
     {"Freeciv server", "xterm -e freeciv-server", "/usr/share//icons/hicolor/16x16/apps/freeciv-server.png" },
     {"Frozen Bubble", "/usr/bin/vendor_perl/frozen-bubble", "/usr/share/pixmaps/frozen-bubble.png" },
     {"Mari0", "mari0"},
     {"Nethack", "xterm -e nethack"},
     {"OpenTTD", "openttd", "/usr/share//icons/hicolor/16x16/apps/openttd.png" },
     {"PCSX", "pcsx", "/usr/share/pixmaps/pcsx-icon.png" },
     {"PCSX2", "pcsx2", "/usr/share/pixmaps/pcsx2.xpm" },
     {"Scorched3d", "scorched3d", "/usr/share//icons/hicolor/48x48/apps/scorched3d.png" },
     {"SpringLobby", "springlobby"},
     {"Steam", "/usr/bin/steam ", "/usr/share//icons/hicolor/16x16/apps/steam.png" },
     {"Zsnes", "zsnes", "/usr/share/pixmaps/zsnes.png" },
 }

 menud334dfcea59127bedfcdbe0a3ee7f494 = {     {"Blender", "blender", "/usr/share//icons/hicolor/16x16/apps/blender.png" },
     {"E-book Viewer", "ebook-viewer ", "/usr/share/pixmaps/calibre-viewer.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share//icons/hicolor/16x16/apps/gimp.png" },
     {"Inkscape", "inkscape ", "/usr/share//icons/hicolor/16x16/apps/inkscape.png" },
     {"LRF Viewer", "lrfviewer ", "/usr/share/pixmaps/calibre-viewer.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Mirage", "mirage ", "/usr/share/pixmaps/mirage.png" },
     {"Ristretto Image Viewer", "ristretto ", "/usr/share//icons/hicolor/16x16/apps/ristretto.png" },
     {"feh", "feh ", "///usr/share/feh/images/logo.svg" },
 }

 menuc8205c7636e728d448c2774e6a4a944b = {     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Chromium", "chromium ", "/home/jeremy/.icons/chromium.png" },
     {"Claws Mail", "claws-mail ", "/usr/share//icons/hicolor/48x48/apps/claws-mail.png" },
     {"EtherApe", "etherape", "/usr/share/pixmaps/etherape.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/home/jeremy/.icons/firefox.png" },
     {"Gwibber", "gwibber ", "/usr/share//icons/hicolor/16x16/apps/gwibber.png" },
     {"Liferea", "liferea", "/usr/share//icons/hicolor/16x16/apps/liferea.png" },
     {"Links", "xlinks -g", "/usr/share/pixmaps/links_32x32.xpm" },
     {"Luakit", "luakit ", "/usr/share/pixmaps/luakit.png" },
     {"Midori", "midori ", "/usr/share//icons/hicolor/16x16/apps/midori.png" },
     {"Midori Private Browsing", "midori --private ", "/usr/share//icons/hicolor/16x16/apps/midori.png" },
     {"Pidgin Internet Messenger", "pidgin", "/usr/share//icons/hicolor/16x16/apps/pidgin.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share//icons/hicolor/16x16/apps/steam.png" },
     {"Wicd", "/usr/bin/wicd-client", "/usr/share//icons/hicolor/16x16/apps/wicd-gtk.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
 }

 menudf814135652a5a308fea15bff37ea284 = {     {"AbiWord", "abiword", "/usr/share//icons/abiword_48.png" },
     {"Calibre", "calibre", "/usr/share/pixmaps/calibre-gui.png" },
     {"Claws Mail", "claws-mail ", "/usr/share//icons/hicolor/48x48/apps/claws-mail.png" },
     {"Dictionary", "xfce4-dict"},
     {"GnuCash", "gnucash ", "/usr/share//icons/hicolor/16x16/apps/gnucash-icon.png" },
     {"Gnumeric", "gnumeric ", "/usr/share//icons/hicolor/16x16/apps/gnumeric.png" },
     {"LibreOffice ", "libreoffice ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Orage Calendar", "orage", "/usr/share//icons/hicolor/48x48/apps/xfcalendar.png" },
     {"Orage Globaltime", "globaltime", "/usr/share//icons/hicolor/48x48/apps/orage_globaltime.png" },
     {"Xpdf", "xpdf ", "/usr/share/pixmaps/xpdf.xpm" },
 }

 menu6311ae17c1ee52b36e68aaf4ad066387 = {     {"ARandR", "arandr", "/usr/share//icons/gnome/16x16/devices/display.png" },
     {"Awn Settings", "awn-settings", "/usr/share//icons/hicolor/48x48/apps/awn-settings.png" },
     {"Broadcast Preferences", "gwibber-preferences", "/usr/share//icons/hicolor/16x16/apps/gwibber.png" },
     {"Celestia", "celestia", "/usr/share/pixmaps/celestia.png" },
     {"Customize Look and Feel", "lxappearance", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-theme.png" },
     {"File Manager", "thunar-settings", "/usr/share//icons/gnome/16x16/apps/system-file-manager.png" },
     {"Online Accounts", "credentials-preferences", "/usr/share//icons/hicolor/16x16/apps/credentials-preferences.png" },
     {"Openbox Configuration Manager", "obconf ", "/usr/share/pixmaps/obconf.png" },
     {"Removable Drives and Media", "thunar-volman-settings", "/usr/share//icons/gnome/16x16/devices/drive-removable-media.png" },
     {"Screensaver", "xscreensaver-demo", "/usr/share//icons/gnome/16x16/apps/xscreensaver.png" },
     {"Sqliteman", "sqliteman "},
     {"dosbox Emulator", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"i3", "i3"},
 }

 menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {     {"Code::Blocks IDE", "codeblocks ", "/usr/share/pixmaps/codeblocks.png" },
     {"DrRacket", "drracket", "/usr/share/pixmaps/drracket.xpm" },
     {"Emacs", "emacs ", "/usr/share//icons/hicolor/16x16/apps/emacs.png" },
     {"FLUID", "fluid ", "/usr/share//icons/hicolor/16x16/apps/fluid.png" },
     {"GNU Octave", "xterm -e /usr/bin/octave", "///usr/share/octave/3.6.3/imagelib/octave-logo.svg" },
     {"Geany", "geany ", "/usr/share//icons/hicolor/16x16/apps/geany.png" },
     {"MATLAB R2012a", "matlab -glnx86 -desktop -nosplash", "///usr/share/icons/matlab.png" },
     {"OpenJDK Monitoring & Management Console", "/usr/bin/jconsole", "/usr/share//icons/hicolor/16x16/apps/java.png" },
     {"OpenJDK Policy Tool", "/usr/bin/policytool", "/usr/share//icons/hicolor/16x16/apps/java.png" },
     {"Qt Assistant", "/usr/bin/assistant", "/usr/share//icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "/usr/bin/designer", "/usr/share//icons/hicolor/128x128/apps/designer.png" },
     {"Qt Linguist", "/usr/bin/linguist", "/usr/share//icons/hicolor/16x16/apps/linguist.png" },
 }

 menu52dd1c847264a75f400961bfb4d1c849 = {     {"Audacity", "audacity ", "/usr/share//icons/hicolor/16x16/apps/audacity.png" },
     {"Audio Mixer", "xfce4-mixer", "/usr/share//icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"ElectricSheep", "electricsheep"},
     {"Gnash SWF Viewer", "gnash-gtk-launcher ", "/usr/share//icons/hicolor/32x32/apps/gnash.xpm" },
     {"QT V4L2 test Utility", "qv4l2", "/usr/share//icons/hicolor/16x16/apps/qv4l2.png" },
     {"Sonata", "sonata", "/usr/share/pixmaps/sonata.png" },
 }

 menuee69799670a33f75d45c57d1d1cd0ab3 = {     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Batti", "batti", "/usr/share//icons/hicolor/16x16/apps/batti.png" },
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share//icons/hicolor/16x16/apps/Thunar.png" },
     {"Cairo-Dock (no OpenGL)", "cairo-dock -c", "/usr/share/pixmaps/cairo-dock.svg" },
     {"EtherApe", "etherape", "/usr/share/pixmaps/etherape.png" },
     {"GLX-Dock (Cairo-Dock with OpenGL)", "cairo-dock", "/usr/share/pixmaps/cairo-dock.svg" },
     {"GParted", "gparted-pkexec", "/usr/share//icons/hicolor/16x16/apps/gparted.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share//icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"System Profiler and Benchmark", "hardinfo", "///usr/share/hardinfo/pixmaps/logo.png" },
     {"Task Manager", "xfce4-taskmanager", "/usr/share//icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Thunar File Manager", "thunar ", "/usr/share//icons/hicolor/16x16/apps/Thunar.png" },
     {"TrueCrypt", "truecrypt", "/usr/share/pixmaps/truecrypt.xpm" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfce Terminal", "xfce4-terminal", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"dconf Editor", "dconf-editor", "/usr/share//icons/hicolor/32x32/apps/dconf-editor.png" },
     {"urxvt", "urxvt", "/home/jeremy/.icons/terminal.png" },
     {"urxvt (client)", "urxvtc", "/home/jeremy/.icons/terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/home/jeremy/.icons/terminal.png" },
 }

 menud146f3eb249e9b43bd562738e9ef02a7 = {     {"CellWriter", "cellwriter", "/usr/share/pixmaps/cellwriter.xpm" },
     {"Easystroke Gesture Recognition", "easystroke"},
 }

xdgmenu = {    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
    {"Universal Access", menud146f3eb249e9b43bd562738e9ef02a7},
}

