 menu98edb85b00d9527ad5acebe451b3fae6 = {     {"7-Zip FM", "7zFM"},
     {"Application Finder", "xfce4-appfinder"},
     {"Avant Window Navigator", "avant-window-navigator"},
     {"Calculator", "gcalctool"},
     {"Character Map", "gucharmap"},
     {"KeePassX", "keepassx ", "/usr/share/pixmaps/keepassx.xpm" },
     {"Leafpad", "leafpad ", "/usr/share/pixmaps/leafpad.png" },
     {"Orage Globaltime", "globaltime"},
     {"Parcellite", "parcellite", "/usr/share/pixmaps/parcellite.png" },
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"Screenshot", "xfce4-screenshooter"},
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"Xarchiver", "xarchiver"},
     {"Xournal", "xournal "},
     {"gedit", "gedit "},
 }

 menude7a22a0c94aa64ba2449e520aa20c99 = {     {"DrRacket", "drracket", "/usr/share/pixmaps/drracket.xpm" },
     {"R", "xterm -e R", "///usr/share/pixmaps/r.png" },
     {"Stellarium nightsky renderer", "stellarium", "/usr/share/pixmaps/stellarium.png" },
 }

 menu251bd8143891238ecedc306508e29017 = {     {"Battle for Wesnoth", "wesnoth", "/usr/share/pixmaps/wesnoth-icon.png" },
     {"Battle for Wesnoth Map Editor", "wesnoth -e", "/usr/share/pixmaps/wesnoth_editor-icon.png" },
     {"DeSmuME (Gtk)", "desmume", "/usr/share/pixmaps/DeSmuME.xpm" },
     {"DeSmuME (Gtk-Glade)", "desmume-glade", "/usr/share/pixmaps/DeSmuME.xpm" },
     {"Dwarf Fortress", "dwarffortress", "///usr/share/pixmaps/dwarffortress.png" },
     {"Dwarf Therapist", "dwarftherapist"},
     {"FreeCol", "freecol", "///usr/share/pixmaps/freecol.xpm" },
     {"Freeciv", "freeciv-gtk2", "/usr/share/pixmaps/freeciv-client.png" },
     {"Freeciv modpack installer", "freeciv-modpack"},
     {"Freeciv server", "xterm -e freeciv-server"},
     {"Frozen Bubble", "/usr/bin/vendor_perl/frozen-bubble", "/usr/share/pixmaps/frozen-bubble.png" },
     {"Hedgewars", "hedgewars", "/usr/share/pixmaps/hedgewars.png" },
     {"Mari0", "mari0"},
     {"Nethack", "xterm -e nethack"},
     {"OpenTTD", "openttd"},
     {"PCSX", "pcsx", "/usr/share/pixmaps/pcsx-icon.png" },
     {"Scorched3d", "scorched3d", "/usr/share/pixmaps/scorched3d.png" },
     {"SpringLobby", "springlobby"},
     {"Steam", "/usr/bin/steam ", "/usr/share/pixmaps/steam.png" },
     {"Zsnes", "zsnes", "/usr/share/pixmaps/zsnes.png" },
 }

 menud334dfcea59127bedfcdbe0a3ee7f494 = {     {"Blender", "blender"},
     {"E-book Viewer", "ebook-viewer ", "/usr/share/pixmaps/calibre-viewer.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 "},
     {"Inkscape", "inkscape "},
     {"LRF Viewer", "lrfviewer ", "/usr/share/pixmaps/calibre-viewer.png" },
     {"LibreOffice Draw", "libreoffice --draw "},
     {"Mirage", "mirage ", "/usr/share/pixmaps/mirage.png" },
     {"Ristretto Image Viewer", "ristretto "},
     {"feh", "feh ", "///usr/share/feh/images/logo.svg" },
 }

 menuc8205c7636e728d448c2774e6a4a944b = {     {"Avahi SSH Server Browser", "/usr/bin/bssh"},
     {"Avahi VNC Server Browser", "/usr/bin/bvnc"},
     {"Chromium", "chromium ", "/home/jeremy/.icons/chromium.png" },
     {"Claws Mail", "claws-mail "},
     {"EtherApe", "etherape", "/usr/share/pixmaps/etherape.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/home/jeremy/.icons/firefox.png" },
     {"Gwibber", "gwibber "},
     {"Liferea", "liferea"},
     {"Links", "xlinks -g", "/usr/share/pixmaps/links_32x32.xpm" },
     {"Luakit", "luakit ", "/usr/share/pixmaps/luakit.png" },
     {"Midori", "midori "},
     {"Midori Private Browsing", "midori --private "},
     {"Pidgin Internet Messenger", "pidgin"},
     {"Steam", "/usr/bin/steam ", "/usr/share/pixmaps/steam.png" },
     {"Tor-Browser (en-US)", "/usr/bin/tor-browser-en", "///usr/share/pixmaps/tor-browser-en.png" },
     {"Wicd", "/usr/bin/wicd-client", "/usr/share/pixmaps/wicd-gtk.xpm" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
 }

 menudf814135652a5a308fea15bff37ea284 = {     {"AbiWord", "abiword"},
     {"Calibre", "calibre", "/usr/share/pixmaps/calibre-gui.png" },
     {"Claws Mail", "claws-mail "},
     {"Dictionary", "xfce4-dict"},
     {"GnuCash", "gnucash "},
     {"Gnumeric", "gnumeric "},
     {"LibreOffice", "libreoffice "},
     {"LibreOffice Base", "libreoffice --base "},
     {"LibreOffice Calc", "libreoffice --calc "},
     {"LibreOffice Draw", "libreoffice --draw "},
     {"LibreOffice Impress", "libreoffice --impress "},
     {"LibreOffice Writer", "libreoffice --writer "},
     {"Orage Calendar", "orage"},
     {"Orage Globaltime", "globaltime"},
     {"Xpdf", "xpdf ", "/usr/share/pixmaps/xpdf.xpm" },
 }

 menu6311ae17c1ee52b36e68aaf4ad066387 = {     {"ARandR", "arandr"},
     {"Awn Settings", "awn-settings"},
     {"Broadcast Preferences", "gwibber-preferences"},
     {"Celestia", "celestia", "/usr/share/pixmaps/celestia.png" },
     {"Customize Look and Feel", "lxappearance"},
     {"File Manager", "thunar-settings"},
     {"Online Accounts", "credentials-preferences"},
     {"Openbox Configuration Manager", "obconf ", "/usr/share/pixmaps/obconf.png" },
     {"Removable Drives and Media", "thunar-volman-settings"},
     {"Screensaver", "xscreensaver-demo", "/usr/share/pixmaps/xscreensaver.xpm" },
     {"Sqliteman", "sqliteman "},
     {"dosbox Emulator", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"i3", "i3"},
 }

 menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {     {"Code::Blocks IDE", "codeblocks ", "/usr/share/pixmaps/codeblocks.png" },
     {"DrRacket", "drracket", "/usr/share/pixmaps/drracket.xpm" },
     {"Emacs", "emacs "},
     {"FLUID", "fluid "},
     {"GNU Octave", "xterm -e /usr/bin/octave", "///usr/share/octave/3.6.3/imagelib/octave-logo.svg" },
     {"Geany", "geany "},
     {"MATLAB R2012a", "matlab -glnx86 -desktop -nosplash", "///usr/share/icons/matlab.png" },
     {"OpenJDK Monitoring & Management Console", "/usr/bin/jconsole"},
     {"OpenJDK Policy Tool", "/usr/bin/policytool"},
 }

 menu52dd1c847264a75f400961bfb4d1c849 = {     {"Audacity", "audacity ", "/usr/share/pixmaps/audacity.xpm" },
     {"Audio Mixer", "xfce4-mixer"},
     {"ElectricSheep", "electricsheep"},
     {"Gnash SWF Viewer", "gnash-gtk-launcher "},
     {"QT V4L2 test Utility", "qv4l2"},
     {"SMPlayer", "smplayer "},
     {"Sonata", "sonata", "/usr/share/pixmaps/sonata.png" },
 }

 menuee69799670a33f75d45c57d1d1cd0ab3 = {     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover"},
     {"Batti", "batti"},
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename "},
     {"Cairo-Dock (no OpenGL)", "cairo-dock -c", "/usr/share/pixmaps/cairo-dock.svg" },
     {"EtherApe", "etherape", "/usr/share/pixmaps/etherape.png" },
     {"GLX-Dock (Cairo-Dock with OpenGL)", "cairo-dock", "/usr/share/pixmaps/cairo-dock.svg" },
     {"GParted", " /usr/sbin/gparted "},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"Oracle VM VirtualBox", "VirtualBox "},
     {"System Profiler and Benchmark", "hardinfo", "///usr/share/hardinfo/pixmaps/logo.png" },
     {"Task Manager", "xfce4-taskmanager"},
     {"Thunar File Manager", "thunar "},
     {"TrueCrypt", "truecrypt", "/usr/share/pixmaps/truecrypt.xpm" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfce Terminal", "xfce4-terminal"},
     {"dconf Editor", "dconf-editor"},
     {"urxvt", "urxvt", "/home/jeremy/.icons/terminal.png" },
     {"urxvt (client)", "urxvtc", "/home/jeremy/.icons/terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/home/jeremy/.icons/terminal.png" },
 }

 menud146f3eb249e9b43bd562738e9ef02a7 = {     {"CellWriter", "cellwriter", "/usr/share/pixmaps/cellwriter.xpm" },
     {"Easystroke Gesture Recognition", "easystroke"},
 }

xdgmenu = {    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
    {"Universal Access", menud146f3eb249e9b43bd562738e9ef02a7},
}

